import { NewsArticle, NewsCategory } from '../types/news';

export const categories: NewsCategory[] = [
  { id: 'all', name: 'Todas', color: 'bg-gray-100 text-gray-800', icon: 'Globe' },
  { id: 'politics', name: 'Política', color: 'bg-blue-100 text-blue-800', icon: 'Vote' },
  { id: 'technology', name: 'Tecnologia', color: 'bg-purple-100 text-purple-800', icon: 'Cpu' },
  { id: 'sports', name: 'Esportes', color: 'bg-green-100 text-green-800', icon: 'Trophy' },
  { id: 'economy', name: 'Economia', color: 'bg-orange-100 text-orange-800', icon: 'TrendingUp' },
  { id: 'world', name: 'Mundo', color: 'bg-red-100 text-red-800', icon: 'MapPin' }
];

export const mockNews: NewsArticle[] = [
  {
    id: '1',
    title: 'Breakthrough in Quantum Computing Achieved by Tech Giant',
    summary: 'Major advancement in quantum computing promises to revolutionize data processing and cybersecurity.',
    content: 'Scientists have announced a significant breakthrough in quantum computing that could transform how we process information...',
    category: 'technology',
    imageUrl: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=800',
    publishedAt: new Date('2025-01-15T10:30:00'),
    author: 'Dr. Sarah Johnson',
    source: 'TechNews Daily',
    isVerified: true,
    verificationScore: 95,
    sources: ['MIT Technology Review', 'Nature Journal', 'IEEE Spectrum'],
    tags: ['quantum', 'computing', 'technology', 'breakthrough'],
    viewCount: 15420,
    isViral: true
  },
  {
    id: '2',
    title: 'Global Climate Summit Reaches Historic Agreement',
    summary: 'World leaders unite on comprehensive climate action plan with binding commitments for 2025.',
    content: 'In an unprecedented move, representatives from 195 countries have reached a historic agreement...',
    category: 'world',
    imageUrl: 'https://images.pexels.com/photos/9324569/pexels-photo-9324569.jpeg?auto=compress&cs=tinysrgb&w=800',
    publishedAt: new Date('2025-01-14T16:45:00'),
    author: 'Maria Rodriguez',
    source: 'Global News Network',
    isVerified: true,
    verificationScore: 92,
    sources: ['UN Climate Change', 'Reuters', 'Associated Press'],
    tags: ['climate', 'environment', 'politics', 'global'],
    viewCount: 28350,
    isViral: true
  },
  {
    id: '3',
    title: 'Revolutionary Treatment for Rare Disease Shows Promise',
    summary: 'Clinical trials demonstrate 90% success rate in treating previously incurable condition.',
    content: 'Medical researchers have announced promising results from phase 3 clinical trials...',
    category: 'technology',
    imageUrl: 'https://images.pexels.com/photos/3938023/pexels-photo-3938023.jpeg?auto=compress&cs=tinysrgb&w=800',
    publishedAt: new Date('2025-01-14T09:15:00'),
    author: 'Dr. Michael Chen',
    source: 'Medical Journal Weekly',
    isVerified: true,
    verificationScore: 88,
    sources: ['The Lancet', 'New England Journal of Medicine', 'FDA Reports'],
    tags: ['medicine', 'health', 'research', 'breakthrough'],
    viewCount: 12750,
    isViral: false
  },
  {
    id: '4',
    title: 'Major Economic Policy Changes Announced',
    summary: 'Central bank introduces new measures to combat inflation and stimulate growth.',
    content: 'The Federal Reserve has announced a series of new policy measures designed to...',
    category: 'economy',
    imageUrl: 'https://images.pexels.com/photos/6801648/pexels-photo-6801648.jpeg?auto=compress&cs=tinysrgb&w=800',
    publishedAt: new Date('2025-01-13T14:20:00'),
    author: 'Robert Wilson',
    source: 'Financial Times',
    isVerified: true,
    verificationScore: 91,
    sources: ['Federal Reserve', 'Bloomberg', 'Wall Street Journal'],
    tags: ['economy', 'finance', 'policy', 'inflation'],
    viewCount: 9840,
    isViral: false
  },
  {
    id: '5',
    title: 'Championship Final Breaks Viewership Records',
    summary: 'Historic match draws largest global audience in sports history.',
    content: 'The championship final between two legendary teams has shattered all previous...',
    category: 'sports',
    imageUrl: 'https://images.pexels.com/photos/46798/the-ball-stadion-football-the-pitch-46798.jpeg?auto=compress&cs=tinysrgb&w=800',
    publishedAt: new Date('2025-01-13T21:30:00'),
    author: 'Alex Thompson',
    source: 'Sports Central',
    isVerified: true,
    verificationScore: 94,
    sources: ['ESPN', 'Sky Sports', 'FIFA Official'],
    tags: ['sports', 'championship', 'records', 'football'],
    viewCount: 45680,
    isViral: true
  },
  {
    id: '6',
    title: 'Space Mission Discovers Potential Signs of Life',
    summary: 'Mars rover findings suggest possible microbial activity in subsurface samples.',
    content: 'NASA scientists analyzing data from the latest Mars mission have discovered...',
    category: 'technology',
    imageUrl: 'https://images.pexels.com/photos/87651/earth-blue-planet-globe-planet-87651.jpeg?auto=compress&cs=tinysrgb&w=800',
    publishedAt: new Date('2025-01-12T11:00:00'),
    author: 'Dr. Lisa Park',
    source: 'Space Today',
    isVerified: true,
    verificationScore: 89,
    sources: ['NASA', 'Space.com', 'Scientific American'],
    tags: ['space', 'mars', 'life', 'discovery'],
    viewCount: 33210,
    isViral: true
  }
];